### ISSUE TITLE
Interpretation of training data

### ISSUE THREAD

**Issue by hnhaefliger** [commaai/calib_challenge#11]
![Figure_1](https://user-images.githubusercontent.com/54628404/134067820-00dc547a-68c8-4efb-8478-27e24b12df25.png)
This is the graph of the yaw in the first video, in which the car drives straight, slowly turns left, and then goes straight again.

How does this translate into a trajectory?

**Comment by haraschax** [comment]
I'm don't understand the question. I tried my best to explain it in the readme

**Comment by hnhaefliger** [comment]
How would I use this data to draw the trajectory of the car? Assuming that the velocity is approximately constant which seems reasonable based on the video (0). Looking at the plot, it seems to me that this is the actual direction of the car relative to a fixed zero and not the change in direction of the car. But if this is the case, then how do we know the initial direction of the car in the testing data?

**Comment by alexriedel1** [comment]
The orientation of the car doesn't matter but only the orientation of the camera (if I got that right...)

**Comment by neel04** [comment]
@alexriedel1 Are you sure it's the orientation of the camera? I am slightly confused about this challenge... logically it makes sense for it to be the camera, just trying to confirm 😃
