### ISSUE TITLE
Number of frames matches number of rows in the txt file

### ISSUE THREAD

**Issue by Shade5** [commaai/calib_challenge#14]
But if you're estimating direction of travel, you need to at least look at a pair of images.
So for N images, only N-1 direction of travel vectors can be estimated. Please confirm if I'm missing something.

Is the first row in the txt file the direction of travel from frame 0 -> 1?

**Comment by haraschax** [comment]
You may need multiple frames to effectively estimate the direction of travel, but at the time of every frame, there is a correct direction of travel, so it is still meaningful to estimate it per frame.
