### ISSUE TITLE
text files contain nan

### ISSUE THREAD

**Issue by mmajewsk** [commaai/calib_challenge#3]
Hi so in this text file https://github.com/commaai/calib_challenge/blob/main/labeled/3.txt#L407 there is plenty of nan's. 
As far as I cen tell the video seems ok in those timestamps.
Since this challenge is quite new, could you confirm that this is intentional?

**Comment by barlowtwin** [comment]
Whenever the speed of car is less then 4 m/s, the corresponding value in the text file for that frame is NaN. Those frames can be ignored I think or you can interpolate the values (not sure if interpolation is a good choice though).
