### ISSUE TITLE
Is the challenge still going on or is it over?

### ISSUE THREAD

**Issue by apoorvumang** [commaai/calib_challenge#4]
I have mailed a submission but haven't received a reply yet (possibly because of the weekend). I was wondering whether the challenge was over already (the money part)

**Comment by haraschax** [comment]
We just started looking in the submissions from the weekend. There may have been a winner. Will update the readme when we've reviewed it.

**Comment by haraschax** [comment]
Prize has been claimed

**Comment by dt1729** [comment]
Does this mean the challenge is still open for internship hiring?

**Comment by haraschax** [comment]
Yes
