### ISSUE TITLE
4.hevc has 1200 frames, but 4.txt only has 1196 datapoints

### ISSUE THREAD

**Issue by creikey** [commaai/calib_challenge#6]

**Comment by haraschax** [comment]
That video only has 1196 frames

> ffprobe -show_packets   4.hevc 2>/dev/null | grep video | wc -l

**Comment by saitishmukhametov** [comment]
if you use opencv in python, you might add cv2.FFMPEG to a VideoCapture args, that will give the right amount of frames in the end
