### ISSUE TITLE
focal length =? picture resolution

### ISSUE THREAD

**Issue by thecodingsophist** [commaai/calib_challenge#8]
When you say focal length in the readme, do you mean picture resolution?

I think that's might be what you mean! Simple clarification ^^ THANKS

**Comment by thecodingsophist** [comment]
If indeed focal length is x pixels, what are the size of the pixels? THANKS

**Comment by bowrango** [comment]
The videos are shot at a resolution of (874, 1164). The focal length of the camera is 910 pixels.
