### ISSUE TITLE
Meaning of direction of motion in camera frame ?

### ISSUE THREAD

**Issue by barlowtwin** [commaai/calib_challenge#9]
Hi all,

Does the direction of motion in camera frame is equivalent to optical flow ?

**Comment by haraschax** [comment]
Direction of motion is described with 3D unit vectors

**Comment by neel04** [comment]
@HaraldSchafer So what is the challenge exactly? Are we supposed to estimate pitch and yaw for the `Comma` device, or are we supposed to estimate that for the car??

**Comment by haraschax** [comment]
The pitch and yaw of the direction of motion in the frame of the camera.

**Comment by neel04** [comment]
but why would the motion of the car have any pitch and yaw? do you mean the pitch and yaw of the _device_? Could you kindly send me some resources for explaining it properly? :hugs:

**Comment by haraschax** [comment]
Forget about the car, the camera is seeing motion. But the motion isn't straight forward from the cameras perspective, it is some direction mostly forward. The pitch and yaw of that vector in the perspective of the camera, that's the objective :).

**Comment by neel04** [comment]
oooh, now I get it! Thanks a ton for clearing that up @HaraldSchafer :+1:

**Comment by candybit** [comment]
In 0.hevc, around 00:20, you can see that the vehicle is turning left, however it seems like the yaw values do not change much. I would expect a negative value while car is turning left, what am I missing here? Is there any calculation to do on the yaw value to get the actual radians/degrees?

For example, from the 0.txt file:
line 381: yaw = 2.943625804138751134e-02 radians (1.68 degrees)
line 1001: yaw = 3.420292253607126048e-02 radians (1.95 degrees)

there is only a 0.27 degrees difference

**Comment by haraschax** [comment]
You would expect that, but it turns out, that's now how vehicle dynamics works. I was surprised too.
